name: Build TRIDENT

on:
  push:
    branches: [ legacy ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          # Windows builds
          - os: windows-latest
            python: '3.10'
            name: windows-py310
          - os: windows-latest
            python: '3.11'
            name: windows-py311
          # macOS builds  
          - os: macos-latest  
            python: '3.10'
            name: macos-py310
          - os: macos-latest  
            python: '3.11'
            name: macos-py311
          # Linux builds
          - os: ubuntu-latest
            python: '3.10' 
            name: linux-py310
          - os: ubuntu-latest
            python: '3.11' 
            name: linux-py311

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pybind11

    - name: Build
      run: |
        cd cpp
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
    
    - name: Copy built files to add-on directory (Windows)
      if: runner.os == 'Windows'
      run: |
        if not exist "trident_add-on\cpp_build" mkdir trident_add-on\cpp_build
        copy cpp\build\Release\trident*.pyd trident_add-on\cpp_build\ 2>nul || echo "No .pyd files found"
        copy cpp\build\Release\trident*.dll trident_add-on\cpp_build\ 2>nul || echo "No .dll files found"
        copy cpp\build\Release\trident*.lib trident_add-on\cpp_build\ 2>nul || echo "No .lib files found"
        copy cpp\build\Release\trident*.exp trident_add-on\cpp_build\ 2>nul || echo "No .exp files found"
        copy cpp\build\Release\trident*.pdb trident_add-on\cpp_build\ 2>nul || echo "No .pdb files found"
        
    - name: Copy built files to add-on directory (Unix)
      if: runner.os != 'Windows'
      run: |
        mkdir -p trident_add-on/cpp_build
        find cpp/build -name "trident*.so" -exec cp {} trident_add-on/cpp_build/ \; || echo "No .so files found"
        find cpp/build -name "trident*.dylib" -exec cp {} trident_add-on/cpp_build/ \; || echo "No .dylib files found"
    
    - name: Debug - List output files (Windows)
      if: runner.os == 'Windows'
      run: |
        echo "Contents of trident_add-on/cpp_build:"
        dir trident_add-on\cpp_build\ 2>nul || echo "cpp_build directory not found"
        
    - name: Debug - List output files (Unix)
      if: runner.os != 'Windows'
      run: |
        echo "Contents of trident_add-on/cpp_build:"
        ls -la trident_add-on/cpp_build/ || echo "cpp_build directory not found"
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trident-${{ matrix.name }}
        path: trident_add-on/cpp_build/trident*