name: Build TRIDENT

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          # Windows builds
          - os: windows-latest
            python: '3.11'
            name: windows-py311
            arch: amd64
          # macOS Intel builds  
          - os: macos-13
            python: '3.11'
            name: macos-intel-py311
            arch: x86_64
          # macOS Apple Silicon builds
          - os: macos-14
            python: '3.11'
            name: macos-arm64-py311
            arch: arm64
          # Linux builds
          - os: ubuntu-latest
            python: '3.11' 
            name: linux-py311
            arch: x86_64

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pybind11

    - name: Build
      run: |
        cd cpp
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
    
    - name: Create bin directory and copy files (Windows)
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        if not exist "trident_extension\bin" mkdir trident_extension\bin
        echo Searching for and copying .pyd files...
        for /r trident_extension %%f in (_trident*.pyd) do if exist "%%f" (echo Found .pyd: %%f & copy "%%f" "trident_extension\bin\")
        echo Copying other _trident files...
        if exist "trident_extension\_trident.dll" copy "trident_extension\_trident.dll" "trident_extension\bin\"
        if exist "trident_extension\_trident.lib" copy "trident_extension\_trident.lib" "trident_extension\bin\"
        if exist "trident_extension\_trident.exp" copy "trident_extension\_trident.exp" "trident_extension\bin\"
        if exist "trident_extension\_trident.pdb" copy "trident_extension\_trident.pdb" "trident_extension\bin\"
        
    - name: Create bin directory and copy files (Unix)
      if: runner.os != 'Windows'
      run: |
        mkdir -p trident_extension/bin
        echo "Searching for and copying .so files..."
        find . -name "_trident*.so" -type f -exec cp {} trident_extension/bin/ \; -exec echo "Copied: {}" \; 2>/dev/null || echo "No .so files found"
        echo "Copying other _trident files..."
        find trident_extension -maxdepth 1 -name "_trident*" -type f -exec cp {} trident_extension/bin/ \; 2>/dev/null || echo "No additional _trident files found"
    
    - name: Final debug - Show bin contents
      shell: bash
      run: |
        echo "=== Final bin contents ==="
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          cmd //c "dir trident_extension\\bin\\ 2>nul || echo bin is empty"
        else
          ls -la trident_extension/bin/ 2>/dev/null || echo "bin is empty"
        fi
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trident-${{ matrix.name }}
        path: trident_extension/bin/
      continue-on-error: true