name: Build TRIDENT

on:
  push:
    branches: [ legacy ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            python: '3.10'
            name: windows
          - os: macos-latest  
            python: '3.10'
            name: macos
          - os: ubuntu-latest
            python: '3.10' 
            name: linux

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pybind11
    
    - name: Debug - List output files
      run: |
        echo "Contents of trident_add-on:"
        ls -la trident_add-on/ || echo "trident_add-on directory not found"
        echo "Contents of cpp directory:"
        ls -la cpp/
        echo "Contents of build directory:"
        ls -la cpp/build/ || echo "build directory not found"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trident-${{ matrix.name }}
        path: trident_add-on/trident*

    - name: Build
      run: |
        cd cpp
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trident-${{ matrix.name }}
        path: trident_add-on/trident*